# Ansible playbook to deploy fortiwlc_exporter
---
- hosts: all
  gather_facts: false

  vars:
    cd_environment: "{{ lookup('env', 'CI_ENVIRONMENT_SLUG') }}"
    package_version: "{{ lookup('env', 'CI_COMMIT_TAG') }}"

  tasks:
    - name: CD environment
      debug:
        var: cd_environment
  
    - name: Include vars
      include_vars: "deploy/{{ cd_environment }}_vars.yml"

    - name: copy RPM package to host
      copy:
        src: "{{ lookup('fileglob', './rpms/x86_64/fortiwlc-exporter-*.el7.x86_64.rpm') }}"
        dest: /tmp/
      register: copy_result
      when:
        - cd_environment == "testing" or cd_environment == "staging"
    
    - name: install copied RPM package
      yum:
        name: "{{ copy_result.dest }}"
        state: present
      when:
        - cd_environment == "testing" or cd_environment == "staging"
      notify:
        - restart fortiwlc_exporter
  
    - name: expire yum cache to force refreshing repo info
      shell: yum clean expire-cache
      when:
        - cd_environment == "production"

    - name: install package from yum repo
      yum:
        name: "fortiwlc-exporter-{{ package_version }}"
        state: present
        allow_downgrade: yes
        update_cache: yes
      when:
        - cd_environment == "production"
      notify:
        - restart fortiwlc_exporter

    - name: write wlc username
      lineinfile:
        path: /etc/fortiwlc_exporter.yaml
        line: "wlc_username: {{ wlc_username }}"
        regexp: "^wlc_username:\\s"
      no_log: yes
      notify:
        - restart fortiwlc_exporter

    - name: write wlc password
      lineinfile:
        path: /etc/fortiwlc_exporter.yaml
        line: "wlc_password: {{ wlc_password }}"
        regexp: "^wlc_password:\\s"
      no_log: yes
      notify:
        - restart fortiwlc_exporter

    - name: enable fortiwlc_exporter service on boot
      service:
        name: fortiwlc_exporter
        enabled: yes

  handlers: 
    - name: restart fortiwlc_exporter
      service:
        name: fortiwlc_exporter
        state: restarted
