stages:
  - build
  - test
  - publish

variables:
  PIP_INDEX_URL: https://zelenjak.arnes.si/nexus/repository/ArnesGroupPyPI/simple

build_rpm:
  stage: build
  image: zelenjak.arnes.si:5000/arnes/rpmbuild:7
  artifacts:
    paths:
      - rpms/
      - srpms/
    expire_in: 1 hour
  variables:
    LC_ALL: en_US.utf8
  script:
    - yum install -y python34-pip python34-setuptools
    - pip3 install --upgrade bumpversion pyinstaller
    - pip3 install .
    - ./dev-version.sh
    - ./build.sh

test_code:
  stage: test
  image: zelenjak.arnes.si:5000/python:3.6
  script: 
    - pip install pipenv
    - pipenv run python -m pip install pip==18.1
    - pipenv install --dev
    - pipenv run python setup.py test

test_rpm:
  image: zelenjak.arnes.si:5000/arnes/centos:7
  stage: test
  dependencies:
    - build_rpm
  script:
    - yum install -y rpms/*/fortiwlc-exporter*.rpm
    - "[ -f /etc/fortiwlc_exporter.ini ]"
    - "fortiwlc_exporter --version"
    - "fortiwlc_exporter -c /etc/fortiwlc_exporter.ini &"
    - "sleep 2"
    - "curl --fail 'http://localhost:9118/'"

publish_rpm:
  image: zelenjak.arnes.si:5000/arnes/centos:7
  stage: publish
  script:
    - ls -lR ./rpms/
    - >-
      curl -f -u "${NEXUS_USERNAME}:${NEXUS_PASSWORD}"
      --upload-file ./rpms/x86_64/fortiwlc-exporter-*.el7.x86_64.rpm
      https://zelenjak.arnes.si/nexus/repository/ArnesYumCentos7/x86_64/
  only:
    - tags

