stages:
  - test_code
  - build
  - test_package
  - publish
  - deploy

variables:
  PIP_INDEX_URL: https://zelenjak.arnes.si/nexus/repository/ArnesGroupPyPI/simple

lint:
  stage: test_code
  image: zelenjak.arnes.si:5000/python:3.6
  script:
    - pip install poetry
    - poetry install
    - poetry run flake8
    - poetry run black --diff --check .
    #- poetry run pydocstyle fortiwlc_exporter
  tags:
    - generic

test_unit:
  stage: test_code
  image: zelenjak.arnes.si:5000/python:3.6
  script:
    - pip install poetry
    - poetry install
    - poetry run pytest --cov=fortiwlc_exporter tests
  tags:
    - generic

test_promtool:
  stage: test_code
  image: zelenjak.arnes.si:5000/arnes/promtool:latest
  script:
    - promtool check metrics < tests/data/many_clients/result.txt
    - promtool check metrics < tests/data/no_clients/result.txt
    - promtool check metrics < tests/data/one_client/result.txt
  tags:
    - generic

build_rpm:
  stage: build
  image: zelenjak.arnes.si:5000/arnes/rpmbuild:7
  artifacts:
    paths:
      - rpms/
      - srpms/
    expire_in: 1 hour
  variables:
    LC_ALL: en_US.utf8
  script:
    - yum install -y python36 git
    - python3.6 -m ensurepip --default-pip
    - pip3.6 install --upgrade bumpversion poetry
    - ./dev-version.sh
    - ./build.sh
  tags:
    - generic

test_rpm:
  image: zelenjak.arnes.si:5000/arnes/centos:7
  stage: test_package
  dependencies:
    - build_rpm
  script:
    - yum install -y rpms/*/fortiwlc-exporter*.rpm
    - "[ -f /etc/fortiwlc_exporter.yaml ]"
    - "fortiwlc_exporter --version"
    - "fortiwlc_exporter -c /etc/fortiwlc_exporter.yaml &"
    - "sleep 2"
    - "curl --fail 'http://localhost:9118/'"
  tags:
    - generic

publish_rpm:
  image: zelenjak.arnes.si:5000/arnes/centos:7
  stage: publish
  script:
    - ls -lR ./rpms/
    - >-
      curl -f -u "${NEXUS_USERNAME}:${NEXUS_PASSWORD}"
      --upload-file ./rpms/x86_64/fortiwlc-exporter-*.el7.x86_64.rpm
      https://zelenjak.arnes.si/nexus/repository/ArnesYumCentos7/x86_64/
  only:
    - tags
  tags:
    - generic

deploy_to_staging:
  stage: deploy
  tags:
    - cd
    - staging
  environment:
    name: staging
  dependencies: 
    - build_rpm
  variables:
    SSH_DEPLOY_KEY: "$SSH_DEPLOY_KEY_STAGING"
    VAULT_PASSWORD: "$VAULT_PASSWORD_STAGING"
  script:
    - deploy staging
  only:
    - branches

deploy_to_production:
  stage: deploy
  tags:
    - cd
    - production
  environment:
    name: production
  dependencies: 
    - publish_rpm
  variables:
    SSH_DEPLOY_KEY: "$SSH_DEPLOY_KEY_PRODUCTION"
    VAULT_PASSWORD: "$VAULT_PASSWORD_PRODUCTION"
  script:
    - deploy production
  only:
    - tags

