stages:
  - build
  - test
  - upload

build_rpm:
  stage: build
  image: zelenjak.arnes.si:5000/arnes/rpmbuild:7
  artifacts:
    paths:
      - rpms/
    expire_in: 1 hour
  variables:
    LC_ALL: en_US.utf8
  script:
    - yum install -y python34-pip
    - pip3 install --upgrade bumpversion
    - ./dev-version.sh
    - ./build.sh

test_code:
  stage: test
  image: zelenjak.arnes.si:5000/python:3.6
  script: 
    - pip install pipenv
    - pipenv install --dev
    - pipenv run python setup.py test

test_rpm:
  image: zelenjak.arnes.si:5000/arnes/centos:7
  stage: test
  dependencies:
    - build_rpm
  script:
    - yum install -y rpms/*/fortiwlc-exporter*.rpm
    - "[ -f /etc/fortiwlc_exporter.ini ]"
    - "fortiwlc_exporter --version"
    - "fortiwlc_exporter -c /etc/fortiwlc_exporter.ini &"
    - "sleep 2"
    - "curl --fail 'http://localhost:9118/'"

# Upload package to repo 
upload_to_rigljica: 
  stage: upload 
  image: zelenjak.arnes.si:5000/arnes/centos:7 
  script: 
    # Install ssh-agent 
    - yum install -y openssh-clients 
    # Run ssh-agent 
    - eval $(ssh-agent -s) 
    # Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store 
    - ssh-add <(echo "$SSH_PRIVATE_KEY") 
    # disable host key checking (NOTE: makes you susceptible to man-in-the-middle attacks) 
    # WARNING: use only in docker container, if you use it with shell you will overwrite your user's ssh config 
    - mkdir -p ~/.ssh 
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config 
    # Copy all RPMs to rigljica 
    - scp -r rpms/*/*.rpm gitlab@rigljica.arnes.si:rpms/ 
    - scp -r srpms/*.src.rpm gitlab@rigljica.arnes.si:rpms/ 
  only: 
    - tags 
